import type { TrailLog } from "@/types";
import { formatIstDateTime } from "@/lib/format";

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}

const HEADERS = [
  "Date & Time",
  "Action By",
  "Role",
  "Action",
  "Comment / Description",
  "Status",
  "Attachments",
];

function rowsOf(rows: TrailLog[]) {
  return rows.map((r) => [
    formatIstDateTime(r.createdAt),
    r.performedByName,
    r.performerRole,
    r.action,
    r.comment ?? "—",
    r.currentStatus ?? "Open",
    (r.attachments || []).map((a) => a.filename).join(", ") || "—",
  ]);
}

export async function exportTrailToExcel(ticketId: string, rows: TrailLog[], generatedBy: string) {
  const XLSX = await import("xlsx");
  const dataRows = rowsOf(rows);
  const ws = XLSX.utils.aoa_to_sheet([
    ["Telecom Regulatory Authority of India"],
    [`Complete Trail — ${ticketId}`],
    [`Generated By: ${generatedBy}`],
    [`Generated: ${formatIstDateTime(new Date().toISOString())}`],
    [],
    HEADERS,
    ...dataRows,
  ]);
  
  // Set column widths dynamically to prevent alignment truncation
  ws["!cols"] = HEADERS.map((h, colIndex) => {
    let maxLen = h.length;
    for (const row of dataRows) {
      const val = row[colIndex];
      if (val !== undefined && val !== null) {
        const len = String(val).length;
        if (len > maxLen) maxLen = len;
      }
    }
    return { wch: Math.min(Math.max(maxLen + 3, 12), 60) };
  });

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Trail");
  const out = XLSX.write(wb, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
  triggerBlobDownload(
    new Blob([out], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `trail-${ticketId}.xlsx`,
  );
}

export async function exportTrailToPdf(ticketId: string, rows: TrailLog[], generatedBy: string) {
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = (autoTableMod as { default: (doc: unknown, opts: unknown) => void }).default;
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(14);
  doc.text("Telecom Regulatory Authority of India", pageWidth / 2, 30, { align: "center" });
  doc.setFontSize(11);
  doc.text(`Complete Trail — ${ticketId}`, pageWidth / 2, 48, { align: "center" });
  doc.setFontSize(9);
  doc.text(`Generated By: ${generatedBy}`, 40, 70);
  doc.text(`Generated: ${formatIstDateTime(new Date().toISOString())}`, pageWidth - 40, 70, { align: "right" });

  autoTable(doc, {
    startY: 84,
    head: [HEADERS],
    body: rowsOf(rows),
    styles: { fontSize: 8, cellPadding: 4, overflow: "linebreak" },
    headStyles: { fillColor: [0, 68, 139], textColor: 255 },
    columnStyles: { 4: { cellWidth: 220 } }, // widen comment column
    didDrawPage: () => {
      const pageHeight = doc.internal.pageSize.getHeight();
      const pageCount = doc.getNumberOfPages();
      const current = (doc as unknown as { internal: { getCurrentPageInfo: () => { pageNumber: number } } })
        .internal.getCurrentPageInfo().pageNumber;
      doc.setFontSize(8);
      doc.text("Generated From TRAI Complaint Portal", 40, pageHeight - 20);
      doc.text(`Page ${current} of ${pageCount}`, pageWidth - 40, pageHeight - 20, { align: "right" });
    },
  });

  const blob = doc.output("blob");
  triggerBlobDownload(blob, `trail-${ticketId}.pdf`);
}