import { createFileRoute, redirect } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { PageHeader } from "@/components/common/PageHeader";
import { MetricCard } from "@/components/common/MetricCard";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { getSlaMetrics } from "@/services/mock";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import { Timer, TimerReset, Gauge, FileText, FileSpreadsheet, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";
import { exportGeneric } from "@/lib/report-export";
import { useAuth } from "@/lib/auth";
import { useTheme } from "@/hooks/useTheme";

export const Route = createFileRoute("/_app/admin/sla")({
  beforeLoad: () => {
    throw redirect({ to: "/admin/dashboard" });
  },
  component: SlaPage
});

function SlaPage() {
  const { data } = useQuery({ queryKey: ["sla"], queryFn: getSlaMetrics });
  const { session } = useAuth();
  const { theme } = useTheme();
  const [busy, setBusy] = useState<null | "Excel" | "PDF">(null);
  
  if (!data) return null;

  const isDark = theme === "dark";
  const primaryColor = isDark ? "#60a5fa" : "#00448B";
  const successColor = isDark ? "#34d399" : "#1f7a4d";
  const gridColor = isDark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.06)";

  const handleExport = async (kind: "Excel" | "PDF") => {
    if (!data.byDivision?.length && !data.byMember?.length) {
      toast.warning("No SLA records to export. Adjust filters and try again.");
      return;
    }
    setBusy(kind);
    try {
      const stamp = Date.now();
      const summary: [string, string | number][] = [
        ["Avg Assignment Time (hrs)", data.avgAssignmentHours],
        ["Avg Resolution Time (days)", data.avgResolutionDays],
        ["Avg Closure Time (days)", data.avgClosureDays],
        ["Overall SLA %", `${data.overallSlaPct}%`],
        ["Generated By", session?.user?.name ?? "Admin"],
      ];
      const divHeaders = ["Division", "SLA %"];
      const divRows = data.byDivision.map(d => [d.name, `${d.slaPct}%`]);
      const memHeaders = ["Member", "SLA %"];
      const memRows = data.byMember.map(m => [m.name, `${m.slaPct}%`]);

      if (kind === "Excel") {
        await exportGeneric({
          kind: "Excel",
          filename: `sla-report-${stamp}.xlsx`,
          reportName: "SLA Report",
          generatedBy: session?.user?.name ?? "Admin",
          headers: divHeaders,
          data: divRows,
          summary,
          sheets: [
            { name: "Division SLA", headers: divHeaders, data: divRows },
            { name: "Member SLA", headers: memHeaders, data: memRows },
          ],
        });
      } else {
        await exportGeneric({
          kind: "PDF",
          filename: `sla-report-${stamp}.pdf`,
          reportName: "SLA Report",
          generatedBy: session?.user?.name ?? "Admin",
          headers: divHeaders,
          data: [...divRows, ["—", "—"], ...memRows.map(r => [`(Member) ${r[0]}`, r[1]])],
          summary,
        });
      }
      toast.success(`${kind} exported successfully.`);
    } catch (e) {
      toast.error(`${kind} export failed.`);
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader title="SLA Dashboard" subtitle="Service-level adherence across divisions and members." actions={
        <div className="flex gap-2">
          <Button variant="outline" disabled={busy !== null} onClick={() => handleExport("Excel")}>
            {busy === "Excel" ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-1.5 h-4 w-4" />}
            {busy === "Excel" ? "Exporting…" : "Excel"}
          </Button>
          <Button disabled={busy !== null} onClick={() => handleExport("PDF")}>
            {busy === "PDF" ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : <FileText className="mr-1.5 h-4 w-4" />}
            {busy === "PDF" ? "Exporting…" : "PDF"}
          </Button>
        </div>
      } />
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <MetricCard label="Avg Assignment" value={`${data.avgAssignmentHours} hrs`} icon={Timer} accent="primary" />
        <MetricCard label="Avg Resolution" value={`${data.avgResolutionDays} days`} icon={TimerReset} accent="info" />
        <MetricCard label="Avg Closure" value={`${data.avgClosureDays} days`} icon={TimerReset} accent="warn" />
        <MetricCard label="Overall SLA" value={`${data.overallSlaPct}%`} icon={Gauge} accent="success" />
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader><CardTitle className="text-base">SLA % by Division</CardTitle></CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={data.byDivision}>
                <CartesianGrid strokeDasharray="3 3" stroke={gridColor} />
                <XAxis dataKey="name" fontSize={12} stroke={isDark ? "#94a3b8" : "#475569"} />
                <YAxis domain={[0, 100]} fontSize={12} stroke={isDark ? "#94a3b8" : "#475569"} />
                <Tooltip contentStyle={{ backgroundColor: isDark ? "#1e293b" : "#ffffff", borderColor: isDark ? "#334155" : "#e2e8f0", color: isDark ? "#f8fafc" : "#0f172a" }} />
                <Bar dataKey="slaPct" fill={primaryColor} radius={[4,4,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
        <Card>
          <CardHeader><CardTitle className="text-base">SLA % by Member</CardTitle></CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={data.byMember}>
                <CartesianGrid strokeDasharray="3 3" stroke={gridColor} />
                <XAxis dataKey="name" fontSize={11} stroke={isDark ? "#94a3b8" : "#475569"} />
                <YAxis domain={[0, 100]} fontSize={12} stroke={isDark ? "#94a3b8" : "#475569"} />
                <Tooltip contentStyle={{ backgroundColor: isDark ? "#1e293b" : "#ffffff", borderColor: isDark ? "#334155" : "#e2e8f0", color: isDark ? "#f8fafc" : "#0f172a" }} />
                <Bar dataKey="slaPct" fill={successColor} radius={[4,4,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}