import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { PageHeader } from "@/components/common/PageHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { getMisReport, allTickets } from "@/services/mock";
import { MetricCard } from "@/components/common/MetricCard";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import { ClipboardList, FileSpreadsheet, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { exportGeneric } from "@/lib/report-export";
import { useCurrentUser } from "@/lib/auth";
import { formatIstDateTime } from "@/lib/format";

export const Route = createFileRoute("/_app/admin/mis")({ component: MisPage });

function MisPage() {
  const [period, setPeriod] = useState<"Monthly" | "Quarterly" | "Yearly">("Monthly");
  const [exporting, setExporting] = useState<"Excel" | "PDF" | null>(null);
  const user = useCurrentUser();
  const { data } = useQuery({ queryKey: ["mis", period], queryFn: () => getMisReport(period) });

  async function handleExport(kind: "Excel" | "PDF") {
    if (!data) {
      toast.warning("Report not loaded yet.");
      return;
    }
    const tickets = await allTickets();
    if (!tickets.length && !data.byDivision.length) {
      toast.warning("No records found for selected filters.");
      return;
    }
    setExporting(kind);
    try {
      const stamp = Date.now();
      const summary: [string, string | number][] = [
        ["Period", period],
        ["Tickets Created", data.summary.created],
        ["Resolved", data.summary.resolved],
        ["Closed", data.summary.closed],
        ["Generated By", user.name],
        ["Generated Date", formatIstDateTime(new Date().toISOString())],
      ];
      const ticketHeaders = ["Sr No", "Ticket No", "Summary", "Division", "Priority", "Status", "Created By", "Assigned To", "Created (IST)", "Resolved (IST)", "Closed (IST)"];
      const ticketRows = tickets.map((t, i) => [
        i + 1, t.ticketId, t.summary, t.division, t.priority, t.currentStatus,
        t.createdByName, t.currentAssigneeName ?? "—",
        formatIstDateTime(t.createdAt),
        t.resolvedAt ? formatIstDateTime(t.resolvedAt) : "—",
        t.closedAt ? formatIstDateTime(t.closedAt) : "—",
      ]);
      const divHeaders = ["Division", "Ticket Count"];
      const divRows = data.byDivision.map(d => [d.name, d.count]);

      if (kind === "Excel") {
        await exportGeneric({
          kind,
          filename: `mis-report-${period}-${stamp}.xlsx`,
          reportName: `MIS Report — ${period}`,
          generatedBy: user.name,
          headers: ticketHeaders,
          data: ticketRows,
          summary,
          sheets: [
            { name: "Tickets", headers: ticketHeaders, data: ticketRows },
            { name: "Analytics", headers: divHeaders, data: divRows },
          ],
        });
      } else {
        await exportGeneric({
          kind,
          filename: `mis-report-${period}-${stamp}.pdf`,
          reportName: `MIS Report — ${period}`,
          generatedBy: user.name,
          headers: divHeaders,
          data: divRows,
        });
      }
      toast.success(`${kind} export downloaded`);
    } catch (e) {
      toast.error(`${kind} export failed`);
      console.error(e);
    } finally {
      setExporting(null);
    }
  }
  return (
    <div className="space-y-6">
      <PageHeader title="MIS Reports" subtitle="Periodic management information across divisions, employees and tickets." actions={
        <div className="flex gap-2">
          <Button variant="outline" disabled={exporting !== null} onClick={() => handleExport("Excel")}>
            {exporting === "Excel" ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-1.5 h-4 w-4" />}
            {exporting === "Excel" ? "Exporting…" : "Excel"}
          </Button>
          <Button disabled={exporting !== null} onClick={() => handleExport("PDF")}>
            {exporting === "PDF" ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : <FileText className="mr-1.5 h-4 w-4" />}
            {exporting === "PDF" ? "Exporting…" : "PDF"}
          </Button>
        </div>
      } />
      <Tabs value={period} onValueChange={(v) => setPeriod(v as never)}>
        <TabsList>
          <TabsTrigger value="Monthly">Monthly</TabsTrigger>
          <TabsTrigger value="Quarterly">Quarterly</TabsTrigger>
          <TabsTrigger value="Yearly">Yearly</TabsTrigger>
        </TabsList>
        <TabsContent value={period} className="mt-4 space-y-4">
          {data && (
            <>
              <div className="grid gap-4 md:grid-cols-3">
                <MetricCard label="Tickets Created" value={data.summary.created} icon={ClipboardList} accent="primary" />
                <MetricCard label="Resolved" value={data.summary.resolved} icon={ClipboardList} accent="success" />
                <MetricCard label="Closed" value={data.summary.closed} icon={ClipboardList} accent="info" />
              </div>
              <Card>
                <CardHeader><CardTitle className="text-base">Tickets by Division ({period})</CardTitle></CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={280}>
                    <BarChart data={data.byDivision}>
                      <CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" fontSize={12} /><YAxis fontSize={12} />
                      <Tooltip /><Bar dataKey="count" fill="#00448B" radius={[4,4,0,0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
            </>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}