/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUserProfileRouteImport } from './routes/_app.user.profile'
import { Route as AppUserDashboardRouteImport } from './routes/_app.user.dashboard'
import { Route as AppTicketsTicketIdRouteImport } from './routes/_app.tickets.$ticketId'
import { Route as AppL3TicketsRouteImport } from './routes/_app.l3.tickets'
import { Route as AppL3RaisedRouteImport } from './routes/_app.l3.raised'
import { Route as AppL3ProfileRouteImport } from './routes/_app.l3.profile'
import { Route as AppL3DashboardRouteImport } from './routes/_app.l3.dashboard'
import { Route as AppL3AssignmentsRouteImport } from './routes/_app.l3.assignments'
import { Route as AppL2RaisedRouteImport } from './routes/_app.l2.raised'
import { Route as AppL2ProfileRouteImport } from './routes/_app.l2.profile'
import { Route as AppL2DashboardRouteImport } from './routes/_app.l2.dashboard'
import { Route as AppL2AssignmentsRouteImport } from './routes/_app.l2.assignments'
import { Route as AppAdminTotalticketRouteImport } from './routes/_app.admin.totalticket'
import { Route as AppAdminSlaRouteImport } from './routes/_app.admin.sla'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminMisRouteImport } from './routes/_app.admin.mis'
import { Route as AppAdminL3TicketsRouteImport } from './routes/_app.admin.l3-tickets'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'
import { Route as AppUserTicketsIndexRouteImport } from './routes/_app.user.tickets.index'
import { Route as AppL2TicketsIndexRouteImport } from './routes/_app.l2.tickets.index'
import { Route as AppAdminEmployeesIndexRouteImport } from './routes/_app.admin.employees.index'
import { Route as AppUserTicketsNewRouteImport } from './routes/_app.user.tickets.new'
import { Route as AppL2TicketsNewRouteImport } from './routes/_app.l2.tickets.new'
import { Route as AppAdminTicketsNewRouteImport } from './routes/_app.admin.tickets.new'
import { Route as AppAdminEmployeesCreateRouteImport } from './routes/_app.admin.employees.create'
import { Route as AppAdminEmployeesEmpIdEditRouteImport } from './routes/_app.admin.employees.$empId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserProfileRoute = AppUserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppUserDashboardRoute = AppUserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppL3TicketsRoute = AppL3TicketsRouteImport.update({
  id: '/l3/tickets',
  path: '/l3/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppL3RaisedRoute = AppL3RaisedRouteImport.update({
  id: '/l3/raised',
  path: '/l3/raised',
  getParentRoute: () => AppRoute,
} as any)
const AppL3ProfileRoute = AppL3ProfileRouteImport.update({
  id: '/l3/profile',
  path: '/l3/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppL3DashboardRoute = AppL3DashboardRouteImport.update({
  id: '/l3/dashboard',
  path: '/l3/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppL3AssignmentsRoute = AppL3AssignmentsRouteImport.update({
  id: '/l3/assignments',
  path: '/l3/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppL2RaisedRoute = AppL2RaisedRouteImport.update({
  id: '/l2/raised',
  path: '/l2/raised',
  getParentRoute: () => AppRoute,
} as any)
const AppL2ProfileRoute = AppL2ProfileRouteImport.update({
  id: '/l2/profile',
  path: '/l2/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppL2DashboardRoute = AppL2DashboardRouteImport.update({
  id: '/l2/dashboard',
  path: '/l2/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppL2AssignmentsRoute = AppL2AssignmentsRouteImport.update({
  id: '/l2/assignments',
  path: '/l2/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTotalticketRoute = AppAdminTotalticketRouteImport.update({
  id: '/admin/totalticket',
  path: '/admin/totalticket',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSlaRoute = AppAdminSlaRouteImport.update({
  id: '/admin/sla',
  path: '/admin/sla',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMisRoute = AppAdminMisRouteImport.update({
  id: '/admin/mis',
  path: '/admin/mis',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminL3TicketsRoute = AppAdminL3TicketsRouteImport.update({
  id: '/admin/l3-tickets',
  path: '/admin/l3-tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppUserTicketsIndexRoute = AppUserTicketsIndexRouteImport.update({
  id: '/user/tickets/',
  path: '/user/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppL2TicketsIndexRoute = AppL2TicketsIndexRouteImport.update({
  id: '/l2/tickets/',
  path: '/l2/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesIndexRoute = AppAdminEmployeesIndexRouteImport.update({
  id: '/admin/employees/',
  path: '/admin/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserTicketsNewRoute = AppUserTicketsNewRouteImport.update({
  id: '/user/tickets/new',
  path: '/user/tickets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppL2TicketsNewRoute = AppL2TicketsNewRouteImport.update({
  id: '/l2/tickets/new',
  path: '/l2/tickets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTicketsNewRoute = AppAdminTicketsNewRouteImport.update({
  id: '/admin/tickets/new',
  path: '/admin/tickets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesCreateRoute = AppAdminEmployeesCreateRouteImport.update({
  id: '/admin/employees/create',
  path: '/admin/employees/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesEmpIdEditRoute =
  AppAdminEmployeesEmpIdEditRouteImport.update({
    id: '/admin/employees/$empId/edit',
    path: '/admin/employees/$empId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/l3-tickets': typeof AppAdminL3TicketsRoute
  '/admin/mis': typeof AppAdminMisRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/sla': typeof AppAdminSlaRoute
  '/admin/totalticket': typeof AppAdminTotalticketRoute
  '/l2/assignments': typeof AppL2AssignmentsRoute
  '/l2/dashboard': typeof AppL2DashboardRoute
  '/l2/profile': typeof AppL2ProfileRoute
  '/l2/raised': typeof AppL2RaisedRoute
  '/l3/assignments': typeof AppL3AssignmentsRoute
  '/l3/dashboard': typeof AppL3DashboardRoute
  '/l3/profile': typeof AppL3ProfileRoute
  '/l3/raised': typeof AppL3RaisedRoute
  '/l3/tickets': typeof AppL3TicketsRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/user/dashboard': typeof AppUserDashboardRoute
  '/user/profile': typeof AppUserProfileRoute
  '/admin/employees/create': typeof AppAdminEmployeesCreateRoute
  '/admin/tickets/new': typeof AppAdminTicketsNewRoute
  '/l2/tickets/new': typeof AppL2TicketsNewRoute
  '/user/tickets/new': typeof AppUserTicketsNewRoute
  '/admin/employees/': typeof AppAdminEmployeesIndexRoute
  '/l2/tickets/': typeof AppL2TicketsIndexRoute
  '/user/tickets/': typeof AppUserTicketsIndexRoute
  '/admin/employees/$empId/edit': typeof AppAdminEmployeesEmpIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/l3-tickets': typeof AppAdminL3TicketsRoute
  '/admin/mis': typeof AppAdminMisRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/sla': typeof AppAdminSlaRoute
  '/admin/totalticket': typeof AppAdminTotalticketRoute
  '/l2/assignments': typeof AppL2AssignmentsRoute
  '/l2/dashboard': typeof AppL2DashboardRoute
  '/l2/profile': typeof AppL2ProfileRoute
  '/l2/raised': typeof AppL2RaisedRoute
  '/l3/assignments': typeof AppL3AssignmentsRoute
  '/l3/dashboard': typeof AppL3DashboardRoute
  '/l3/profile': typeof AppL3ProfileRoute
  '/l3/raised': typeof AppL3RaisedRoute
  '/l3/tickets': typeof AppL3TicketsRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/user/dashboard': typeof AppUserDashboardRoute
  '/user/profile': typeof AppUserProfileRoute
  '/admin/employees/create': typeof AppAdminEmployeesCreateRoute
  '/admin/tickets/new': typeof AppAdminTicketsNewRoute
  '/l2/tickets/new': typeof AppL2TicketsNewRoute
  '/user/tickets/new': typeof AppUserTicketsNewRoute
  '/admin/employees': typeof AppAdminEmployeesIndexRoute
  '/l2/tickets': typeof AppL2TicketsIndexRoute
  '/user/tickets': typeof AppUserTicketsIndexRoute
  '/admin/employees/$empId/edit': typeof AppAdminEmployeesEmpIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/l3-tickets': typeof AppAdminL3TicketsRoute
  '/_app/admin/mis': typeof AppAdminMisRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/sla': typeof AppAdminSlaRoute
  '/_app/admin/totalticket': typeof AppAdminTotalticketRoute
  '/_app/l2/assignments': typeof AppL2AssignmentsRoute
  '/_app/l2/dashboard': typeof AppL2DashboardRoute
  '/_app/l2/profile': typeof AppL2ProfileRoute
  '/_app/l2/raised': typeof AppL2RaisedRoute
  '/_app/l3/assignments': typeof AppL3AssignmentsRoute
  '/_app/l3/dashboard': typeof AppL3DashboardRoute
  '/_app/l3/profile': typeof AppL3ProfileRoute
  '/_app/l3/raised': typeof AppL3RaisedRoute
  '/_app/l3/tickets': typeof AppL3TicketsRoute
  '/_app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/_app/user/dashboard': typeof AppUserDashboardRoute
  '/_app/user/profile': typeof AppUserProfileRoute
  '/_app/admin/employees/create': typeof AppAdminEmployeesCreateRoute
  '/_app/admin/tickets/new': typeof AppAdminTicketsNewRoute
  '/_app/l2/tickets/new': typeof AppL2TicketsNewRoute
  '/_app/user/tickets/new': typeof AppUserTicketsNewRoute
  '/_app/admin/employees/': typeof AppAdminEmployeesIndexRoute
  '/_app/l2/tickets/': typeof AppL2TicketsIndexRoute
  '/_app/user/tickets/': typeof AppUserTicketsIndexRoute
  '/_app/admin/employees/$empId/edit': typeof AppAdminEmployeesEmpIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/l3-tickets'
    | '/admin/mis'
    | '/admin/reports'
    | '/admin/sla'
    | '/admin/totalticket'
    | '/l2/assignments'
    | '/l2/dashboard'
    | '/l2/profile'
    | '/l2/raised'
    | '/l3/assignments'
    | '/l3/dashboard'
    | '/l3/profile'
    | '/l3/raised'
    | '/l3/tickets'
    | '/tickets/$ticketId'
    | '/user/dashboard'
    | '/user/profile'
    | '/admin/employees/create'
    | '/admin/tickets/new'
    | '/l2/tickets/new'
    | '/user/tickets/new'
    | '/admin/employees/'
    | '/l2/tickets/'
    | '/user/tickets/'
    | '/admin/employees/$empId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/l3-tickets'
    | '/admin/mis'
    | '/admin/reports'
    | '/admin/sla'
    | '/admin/totalticket'
    | '/l2/assignments'
    | '/l2/dashboard'
    | '/l2/profile'
    | '/l2/raised'
    | '/l3/assignments'
    | '/l3/dashboard'
    | '/l3/profile'
    | '/l3/raised'
    | '/l3/tickets'
    | '/tickets/$ticketId'
    | '/user/dashboard'
    | '/user/profile'
    | '/admin/employees/create'
    | '/admin/tickets/new'
    | '/l2/tickets/new'
    | '/user/tickets/new'
    | '/admin/employees'
    | '/l2/tickets'
    | '/user/tickets'
    | '/admin/employees/$empId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin/analytics'
    | '/_app/admin/audit'
    | '/_app/admin/dashboard'
    | '/_app/admin/l3-tickets'
    | '/_app/admin/mis'
    | '/_app/admin/reports'
    | '/_app/admin/sla'
    | '/_app/admin/totalticket'
    | '/_app/l2/assignments'
    | '/_app/l2/dashboard'
    | '/_app/l2/profile'
    | '/_app/l2/raised'
    | '/_app/l3/assignments'
    | '/_app/l3/dashboard'
    | '/_app/l3/profile'
    | '/_app/l3/raised'
    | '/_app/l3/tickets'
    | '/_app/tickets/$ticketId'
    | '/_app/user/dashboard'
    | '/_app/user/profile'
    | '/_app/admin/employees/create'
    | '/_app/admin/tickets/new'
    | '/_app/l2/tickets/new'
    | '/_app/user/tickets/new'
    | '/_app/admin/employees/'
    | '/_app/l2/tickets/'
    | '/_app/user/tickets/'
    | '/_app/admin/employees/$empId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/user/profile': {
      id: '/_app/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof AppUserProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/dashboard': {
      id: '/_app/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof AppUserDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/$ticketId': {
      id: '/_app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l3/tickets': {
      id: '/_app/l3/tickets'
      path: '/l3/tickets'
      fullPath: '/l3/tickets'
      preLoaderRoute: typeof AppL3TicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l3/raised': {
      id: '/_app/l3/raised'
      path: '/l3/raised'
      fullPath: '/l3/raised'
      preLoaderRoute: typeof AppL3RaisedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l3/profile': {
      id: '/_app/l3/profile'
      path: '/l3/profile'
      fullPath: '/l3/profile'
      preLoaderRoute: typeof AppL3ProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l3/dashboard': {
      id: '/_app/l3/dashboard'
      path: '/l3/dashboard'
      fullPath: '/l3/dashboard'
      preLoaderRoute: typeof AppL3DashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l3/assignments': {
      id: '/_app/l3/assignments'
      path: '/l3/assignments'
      fullPath: '/l3/assignments'
      preLoaderRoute: typeof AppL3AssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l2/raised': {
      id: '/_app/l2/raised'
      path: '/l2/raised'
      fullPath: '/l2/raised'
      preLoaderRoute: typeof AppL2RaisedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l2/profile': {
      id: '/_app/l2/profile'
      path: '/l2/profile'
      fullPath: '/l2/profile'
      preLoaderRoute: typeof AppL2ProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l2/dashboard': {
      id: '/_app/l2/dashboard'
      path: '/l2/dashboard'
      fullPath: '/l2/dashboard'
      preLoaderRoute: typeof AppL2DashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l2/assignments': {
      id: '/_app/l2/assignments'
      path: '/l2/assignments'
      fullPath: '/l2/assignments'
      preLoaderRoute: typeof AppL2AssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/totalticket': {
      id: '/_app/admin/totalticket'
      path: '/admin/totalticket'
      fullPath: '/admin/totalticket'
      preLoaderRoute: typeof AppAdminTotalticketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sla': {
      id: '/_app/admin/sla'
      path: '/admin/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AppAdminSlaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/mis': {
      id: '/_app/admin/mis'
      path: '/admin/mis'
      fullPath: '/admin/mis'
      preLoaderRoute: typeof AppAdminMisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/l3-tickets': {
      id: '/_app/admin/l3-tickets'
      path: '/admin/l3-tickets'
      fullPath: '/admin/l3-tickets'
      preLoaderRoute: typeof AppAdminL3TicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/tickets/': {
      id: '/_app/user/tickets/'
      path: '/user/tickets'
      fullPath: '/user/tickets/'
      preLoaderRoute: typeof AppUserTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l2/tickets/': {
      id: '/_app/l2/tickets/'
      path: '/l2/tickets'
      fullPath: '/l2/tickets/'
      preLoaderRoute: typeof AppL2TicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/': {
      id: '/_app/admin/employees/'
      path: '/admin/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AppAdminEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/tickets/new': {
      id: '/_app/user/tickets/new'
      path: '/user/tickets/new'
      fullPath: '/user/tickets/new'
      preLoaderRoute: typeof AppUserTicketsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l2/tickets/new': {
      id: '/_app/l2/tickets/new'
      path: '/l2/tickets/new'
      fullPath: '/l2/tickets/new'
      preLoaderRoute: typeof AppL2TicketsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tickets/new': {
      id: '/_app/admin/tickets/new'
      path: '/admin/tickets/new'
      fullPath: '/admin/tickets/new'
      preLoaderRoute: typeof AppAdminTicketsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/create': {
      id: '/_app/admin/employees/create'
      path: '/admin/employees/create'
      fullPath: '/admin/employees/create'
      preLoaderRoute: typeof AppAdminEmployeesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/$empId/edit': {
      id: '/_app/admin/employees/$empId/edit'
      path: '/admin/employees/$empId/edit'
      fullPath: '/admin/employees/$empId/edit'
      preLoaderRoute: typeof AppAdminEmployeesEmpIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminL3TicketsRoute: typeof AppAdminL3TicketsRoute
  AppAdminMisRoute: typeof AppAdminMisRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSlaRoute: typeof AppAdminSlaRoute
  AppAdminTotalticketRoute: typeof AppAdminTotalticketRoute
  AppL2AssignmentsRoute: typeof AppL2AssignmentsRoute
  AppL2DashboardRoute: typeof AppL2DashboardRoute
  AppL2ProfileRoute: typeof AppL2ProfileRoute
  AppL2RaisedRoute: typeof AppL2RaisedRoute
  AppL3AssignmentsRoute: typeof AppL3AssignmentsRoute
  AppL3DashboardRoute: typeof AppL3DashboardRoute
  AppL3ProfileRoute: typeof AppL3ProfileRoute
  AppL3RaisedRoute: typeof AppL3RaisedRoute
  AppL3TicketsRoute: typeof AppL3TicketsRoute
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppUserDashboardRoute: typeof AppUserDashboardRoute
  AppUserProfileRoute: typeof AppUserProfileRoute
  AppAdminEmployeesCreateRoute: typeof AppAdminEmployeesCreateRoute
  AppAdminTicketsNewRoute: typeof AppAdminTicketsNewRoute
  AppL2TicketsNewRoute: typeof AppL2TicketsNewRoute
  AppUserTicketsNewRoute: typeof AppUserTicketsNewRoute
  AppAdminEmployeesIndexRoute: typeof AppAdminEmployeesIndexRoute
  AppL2TicketsIndexRoute: typeof AppL2TicketsIndexRoute
  AppUserTicketsIndexRoute: typeof AppUserTicketsIndexRoute
  AppAdminEmployeesEmpIdEditRoute: typeof AppAdminEmployeesEmpIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminL3TicketsRoute: AppAdminL3TicketsRoute,
  AppAdminMisRoute: AppAdminMisRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSlaRoute: AppAdminSlaRoute,
  AppAdminTotalticketRoute: AppAdminTotalticketRoute,
  AppL2AssignmentsRoute: AppL2AssignmentsRoute,
  AppL2DashboardRoute: AppL2DashboardRoute,
  AppL2ProfileRoute: AppL2ProfileRoute,
  AppL2RaisedRoute: AppL2RaisedRoute,
  AppL3AssignmentsRoute: AppL3AssignmentsRoute,
  AppL3DashboardRoute: AppL3DashboardRoute,
  AppL3ProfileRoute: AppL3ProfileRoute,
  AppL3RaisedRoute: AppL3RaisedRoute,
  AppL3TicketsRoute: AppL3TicketsRoute,
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppUserDashboardRoute: AppUserDashboardRoute,
  AppUserProfileRoute: AppUserProfileRoute,
  AppAdminEmployeesCreateRoute: AppAdminEmployeesCreateRoute,
  AppAdminTicketsNewRoute: AppAdminTicketsNewRoute,
  AppL2TicketsNewRoute: AppL2TicketsNewRoute,
  AppUserTicketsNewRoute: AppUserTicketsNewRoute,
  AppAdminEmployeesIndexRoute: AppAdminEmployeesIndexRoute,
  AppL2TicketsIndexRoute: AppL2TicketsIndexRoute,
  AppUserTicketsIndexRoute: AppUserTicketsIndexRoute,
  AppAdminEmployeesEmpIdEditRoute: AppAdminEmployeesEmpIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
