import type { Employee, Ticket } from "@/types";
import { formatIstDate, formatIstDateTime } from "@/lib/format";

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}

const EMPLOYEE_HEADERS = [
  "Sr No",
  "Employee ID",
  "Name",
  "Email",
  "Role",
  "Sub Role",
  "Division",
  "Designation",
  "Floor",
  "Status",
  "Created Date (IST)",
  "Updated Date (IST)",
];

const TICKET_HEADERS = [
  "Sr No",
  "Ticket Number",
  "Subject",
  "Division",
  "Priority",
  "Type",
  "Current Status",
  "Created By",
  "Assigned To",
  "Created Date (IST)",
  "Resolved Date (IST)",
  "Closed Date (IST)",
];

function employeeRows(rows: Employee[]) {
  return rows.map((e, i) => [
    i + 1,
    e.empId,
    e.name,
    e.email,
    e.role,
    e.subRole ?? "—",
    e.division,
    e.designation,
    e.floor,
    e.isActive ? "Active" : "Inactive",
    formatIstDateTime(e.createdAt),
    formatIstDateTime(e.updatedAt),
  ]);
}

function ticketRows(rows: Ticket[]) {
  return rows.map((t, i) => [
    i + 1,
    t.ticketId,
    t.summary,
    t.division,
    t.priority,
    t.type,
    t.currentStatus,
    t.createdByName,
    t.currentAssigneeName,
    formatIstDateTime(t.createdAt),
    t.resolvedAt ? formatIstDateTime(t.resolvedAt) : "—",
    t.closedAt ? formatIstDateTime(t.closedAt) : "—",
  ]);
}

async function writeExcel(opts: {
  filename: string;
  reportName: string;
  generatedBy: string;
  headers: string[];
  data: (string | number)[][];
  summary: [string, string | number][];
}) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  const summarySheet = XLSX.utils.aoa_to_sheet([
    ["Telecom Regulatory Authority of India"],
    [opts.reportName],
    [`Generated By: ${opts.generatedBy}`],
    [`Generated: ${formatIstDateTime(new Date().toISOString())}`],
    [],
    ["Metric", "Value"],
    ...opts.summary,
  ]);
  summarySheet["!cols"] = [{ wch: 28 }, { wch: 32 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");

  const dataSheet = XLSX.utils.aoa_to_sheet([opts.headers, ...opts.data]);
  // Calculate column widths dynamically to prevent alignment truncation
  dataSheet["!cols"] = opts.headers.map((h, colIndex) => {
    let maxLen = h.length;
    for (const row of opts.data) {
      const val = row[colIndex];
      if (val !== undefined && val !== null) {
        const len = String(val).length;
        if (len > maxLen) maxLen = len;
      }
    }
    return { wch: Math.min(Math.max(maxLen + 3, 12), 60) };
  });
  XLSX.utils.book_append_sheet(wb, dataSheet, "Data");

  const analyticsSheet = XLSX.utils.aoa_to_sheet([
    ["Analytics"],
    ["Total Records", opts.data.length],
  ]);
  analyticsSheet["!cols"] = [{ wch: 24 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, analyticsSheet, "Analytics");

  const out = XLSX.write(wb, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
  triggerBlobDownload(
    new Blob([out], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    opts.filename,
  );
}

async function writePdf(opts: {
  filename: string;
  reportName: string;
  generatedBy: string;
  headers: string[];
  data: (string | number)[][];
  columnStyles?: any;
}) {
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = (autoTableMod as { default: (doc: unknown, opts: unknown) => void }).default;
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(13);
  doc.text("Telecom Regulatory Authority of India", pageWidth / 2, 30, { align: "center" });
  doc.setFontSize(11);
  doc.text(opts.reportName, pageWidth / 2, 48, { align: "center" });
  doc.setFontSize(9);
  doc.text(`Generated By: ${opts.generatedBy}`, 40, 70);
  doc.text(
    `Generated Date: ${formatIstDateTime(new Date().toISOString())} IST`,
    pageWidth - 40,
    70,
    { align: "right" },
  );
  doc.setLineWidth(0.5);
  doc.line(40, 78, pageWidth - 40, 78);

  autoTable(doc, {
    startY: 88,
    head: [opts.headers],
    body: opts.data,
    styles: { fontSize: 8, cellPadding: 4, overflow: "linebreak" },
    headStyles: { fillColor: [0, 68, 139], textColor: 255 },
    columnStyles: opts.columnStyles,
    didParseCell: (data: any) => {
      if (data.section === "body") {
        const header = opts.headers[data.column.index];
        if (header === "Current Status" || header === "Status") {
          const val = String(data.cell.raw || "");
          if (val === "Open") {
            data.cell.styles.textColor = [0, 102, 204]; // Blue
            data.cell.styles.fontStyle = "bold";
          } else if (val === "Resolved") {
            data.cell.styles.textColor = [31, 122, 77]; // Green
            data.cell.styles.fontStyle = "bold";
          } else if (val === "Closed") {
            data.cell.styles.textColor = [204, 0, 0]; // Red
            data.cell.styles.fontStyle = "bold";
          }
        }
      }
    },
    didDrawPage: () => {
      const pageHeight = doc.internal.pageSize.getHeight();
      const pageCount = doc.getNumberOfPages();
      const current = (
        doc as unknown as { internal: { getCurrentPageInfo: () => { pageNumber: number } } }
      ).internal.getCurrentPageInfo().pageNumber;
      doc.setFontSize(8);
      doc.text("Generated From TRAI Complaint Portal", 40, pageHeight - 20);
      doc.text(`Page ${current} of ${pageCount}`, pageWidth - 40, pageHeight - 20, {
        align: "right",
      });
    },
  });

  triggerBlobDownload(doc.output("blob"), opts.filename);
}

export async function exportEmployees(
  kind: "Excel" | "PDF",
  rows: Employee[],
  generatedBy: string,
) {
  const stamp = formatIstDate(new Date()).replace(/-/g, "");
  const data = employeeRows(rows);
  if (kind === "Excel") {
    await writeExcel({
      filename: `employees-${stamp}.xlsx`,
      reportName: "Employee Report",
      generatedBy,
      headers: EMPLOYEE_HEADERS,
      data,
      summary: [
        ["Total Employees", rows.length],
        ["Active", rows.filter((r) => r.isActive).length],
        ["Inactive", rows.filter((r) => !r.isActive).length],
      ],
    });
  } else {
    await writePdf({
      filename: `employees-${stamp}.pdf`,
      reportName: "Employee Report",
      generatedBy,
      headers: EMPLOYEE_HEADERS,
      data,
    });
  }
}

export async function exportTickets(kind: "Excel" | "PDF", rows: Ticket[], generatedBy: string) {
  const stamp = formatIstDate(new Date()).replace(/-/g, "");
  const data = ticketRows(rows);
  if (kind === "Excel") {
    await writeExcel({
      filename: `tickets-${stamp}.xlsx`,
      reportName: "Ticket Report",
      generatedBy,
      headers: TICKET_HEADERS,
      data,
      summary: [
        ["Total Tickets", rows.length],
        ["Open", rows.filter((r) => r.currentStatus === "Open").length],
        ["Resolved", rows.filter((r) => r.currentStatus === "Resolved").length],
        ["Closed", rows.filter((r) => r.currentStatus === "Closed").length],
      ],
    });
  } else {
    await writePdf({
      filename: `tickets-${stamp}.pdf`,
      reportName: "Ticket Report",
      generatedBy,
      headers: TICKET_HEADERS,
      data,
    });
  }
}

// ---- Generic export ----------------------------------------------------

export async function exportGeneric(opts: {
  kind: "Excel" | "PDF";
  filename: string;
  reportName: string;
  generatedBy: string;
  headers: string[];
  data: (string | number)[][];
  summary?: [string, string | number][];
  sheets?: { name: string; headers: string[]; data: (string | number)[][] }[];
}) {
  if (opts.kind === "Excel") {
    if (opts.sheets && opts.sheets.length) {
      const XLSX = await import("xlsx");
      const wb = XLSX.utils.book_new();
      if (opts.summary) {
        const s = XLSX.utils.aoa_to_sheet([
          ["Telecom Regulatory Authority of India"],
          [opts.reportName],
          [`Generated By: ${opts.generatedBy}`],
          [`Generated: ${formatIstDateTime(new Date().toISOString())}`],
          [],
          ["Metric", "Value"],
          ...opts.summary,
        ]);
        s["!cols"] = [{ wch: 28 }, { wch: 32 }];
        XLSX.utils.book_append_sheet(wb, s, "Summary");
      }
      for (const sh of opts.sheets) {
        const ws = XLSX.utils.aoa_to_sheet([sh.headers, ...sh.data]);
        ws["!cols"] = sh.headers.map(() => ({ wch: 20 }));
        XLSX.utils.book_append_sheet(wb, ws, sh.name.slice(0, 31));
      }
      const out = XLSX.write(wb, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
      triggerBlobDownload(
        new Blob([out], {
          type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        }),
        opts.filename,
      );
      return;
    }
    await writeExcel({
      filename: opts.filename,
      reportName: opts.reportName,
      generatedBy: opts.generatedBy,
      headers: opts.headers,
      data: opts.data,
      summary: opts.summary ?? [["Total Records", opts.data.length]],
    });
  } else {
    await writePdf({
      filename: opts.filename,
      reportName: opts.reportName,
      generatedBy: opts.generatedBy,
      headers: opts.headers,
      data: opts.data,
    });
  }
}

export async function exportAssigneeAssignments(
  kind: "Excel" | "PDF",
  report: any,
  generatedBy: string,
) {
  const stamp = formatIstDate(new Date()).replace(/-/g, "");
  const ASSIGNEE_HEADERS = [
    "Ticket ID",
    "Summary",
    "Assigned At",
    "Assigned By",
    "Assignee",
    "Status",
    "Assignee Actions",
  ];

  const data = report.tickets.map((t: any) => [
    t.ticketId,
    t.summary,
    formatIstDateTime(t.assignedAt),
    `${t.assignedBy.name} (${t.assignedBy.role})`,
    `${report.assignee.name} (${report.assignee.role}/${report.assignee.subrole || "-"})`,
    t.status,
    t.assigneeActions.map((a: any) => a.formatted).join(";\n"),
  ]);

  if (kind === "Excel") {
    await writeExcel({
      filename: `assignee-report-${report.assignee.userId}-${stamp}.xlsx`,
      reportName: `Assignee Assignment Report: ${report.assignee.name}`,
      generatedBy,
      headers: ASSIGNEE_HEADERS,
      data,
      summary: [
        ["Assignee Name", report.assignee.name],
        ["Assignee ID", report.assignee.userId],
        ["From Date", report.fromDate],
        ["To Date", report.toDate],
        ["Total Tickets", report.tickets.length],
      ],
    });
  } else {
    await writePdf({
      filename: `assignee-report-${report.assignee.userId}-${stamp}.pdf`,
      reportName: `Assignee Assignment Report: ${report.assignee.name} (${report.fromDate} to ${report.toDate})`,
      generatedBy,
      headers: ASSIGNEE_HEADERS,
      data,
      columnStyles: {
        1: { cellWidth: 150 }, // Summary
        6: { cellWidth: 250 }, // Assignee Actions
      },
    });
  }
}
